name: appetite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Ajustei para uma versão mais comum e segura

dependencies:
  flutter:
    sdk: flutter

  # --- TODAS AS DEPENDÊNCIAS DEVEM ESTAR ALINHADAS AQUI ---
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  uuid: ^4.4.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.0.0
  mqtt_client: ^10.0.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true