name: appetite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Ajustei para uma versão mais comum e segura

dependencies:
  flutter:
    sdk: flutter

  # --- TODAS AS DEPENDÊNCIAS DE RUNTIME DEVEM ESTAR ALINHADAS AQUI ---
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  uuid: ^4.4.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.0.0
  
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # <--- APENAS AQUI! Remova de 'dependencies' se estava lá.

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon/app_icon.png" # Ícone legado
  # --- Configuração para ícones adaptativos ---
  adaptive_icon_background: "#3D5A5A" # <--- Mude para a cor que você preferir! (ex: turquesa)
  adaptive_icon_foreground: "assets/app_icon/app_icon.png" # Sua logo principal
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Para adicionar assets ao seu aplicativo, adicione uma seção assets, assim:
  assets: # <--- Adicione isto para que o Flutter inclua a pasta assets no app!
    - assets/app_icon/